language: go
go: '1.10'
before_install:
    - go get github.com/mattn/goveralls
    - go get -t -v ./...
install:
    - # skip
before_script:
    - gofmt -d -s .
    - go vet ./...
    - go test -v -race ./...
script:
    - $HOME/gopath/bin/goveralls -service=travis-ci
notifications:
    email: false
